<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Nikita</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-03T18:01:45</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b0f65a7e-04ad-4c33-b1da-d35c611f1257</testSuiteGuid>
   <testCaseLink>
      <guid>3a023508-a064-4676-ae9f-6e2abda97da9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nikita/Orange HRM/Login_Excel_testdata</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4ecee51c-7f7a-4896-9195-f5ff127f338e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/excel_read</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4ecee51c-7f7a-4896-9195-f5ff127f338e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>be6a24c8-1a61-4df5-b4a7-2012a9ee3d4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4ecee51c-7f7a-4896-9195-f5ff127f338e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>1f8acacc-7460-49e8-9203-a21511ff9efe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
