<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-17T10:50:02</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0d1d9818-188c-474c-8e4d-4ed87d29338d</testSuiteGuid>
   <testCaseLink>
      <guid>a4486896-82e4-4d97-b115-68c3a36a8830</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Bhawna/TC_MouseHoverAndScreenshot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7f518c-16b3-48ad-b519-f2c2dfe99041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f49319-677c-45f4-97c6-714f2d8fccf4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
