<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popopClosebtn</name>
   <tag></tag>
   <elementGuidId>fe2eba5d-c3d7-4329-a01f-0ff1fd8a3783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.popupCloseButton</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
