<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Nirmal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3645c4c4-0d32-4f48-93ad-1382c16fc466</testSuiteGuid>
   <testCaseLink>
      <guid>dce39921-1462-44a1-a72d-a0b9dcdcc33b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nirmal/TC1 - File Upload</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>28e96280-4bd9-4c5b-84f0-5eb78b827a77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nirmal/TC2 - File Download And Verification</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>253552f3-89e6-4522-a364-bad7a3333ffe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nirmal/TC3 - Image Comparison Sikuli</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a01446a6-6be4-48e2-9d2d-7152d2aa7baf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nirmal/TC4 - ScreenShotWithCustomKeyWord</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2c30edd5-7e83-45d0-9f08-9f5a5040ed23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nirmal/TC5 - End To End Scenario</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07851a89-24b0-4954-95bf-77bd4203d7d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb854ed6-c917-4fe9-8293-69e7f8096f38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97da52c4-1a16-4fd6-9fef-1bb51282d698</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04c2a6b3-87ab-446c-91a4-bfbbe04d4bc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67fb1d7f-ddc1-4e17-a22a-9e2b19470529</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc1228d7-6fec-4c99-8b89-5a5f66994cb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71febe0b-aca7-4fd3-bf0a-18138ce08140</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741304a2-d68f-445f-803a-b064b38acb00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec592db5-ea82-4237-9c83-8375b7b9deee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e43ad307-1b21-4eb7-9123-69ff5fafc542</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8dd31d8-38c8-4021-a1d9-b7ef17148437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b3f1f55-5c93-4e09-990b-89b99c741786</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7abf566-809a-47e1-bacb-af2c43a1a44c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
