<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Basic_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-17T11:11:00</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>007f27f0-cef3-4ece-a8c5-afed296faba1</testSuiteGuid>
   <testCaseLink>
      <guid>f9b67f0e-390f-4bb6-adcd-923f54ae90fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nikita.A/Basiclogin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12ab0784-f35a-4001-b3a7-f75e759d2cb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b521fef-9a58-401d-869e-f4f436300ac3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
